name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Make changes
        run: |
          echo "Some changes" > file.txt

      - name: Commit changes
        run: |
          git add file.txt
          git commit -m "Automated change"

      - name: Push changes
        run: |
          git push origin HEAD:new-branch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Automated PR"
          body: "This is an automated pull request."
          base: main
          branch: new-branch

