name: Run Daily Script

on:
  schedule:
    # Run the workflow daily at 9 AM EST
    - cron: '0 14 * * *'  # This will run at 9 AM EST during standard time (UTC-5)
    - cron: '0 13 * * *'  # This will run at 9 AM EST during daylight saving time (UTC-4)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access your scripts
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run your script with the secret environment variable
      - name: Run the script
        env:
          TEAMS_ACCESS_TOKEN: ${{ secrets.TEAMS_ACCESS_TOKEN }}
        run: |
          python3 test_chatops.py
