name: Run Daily Script

on:
  schedule:
    # Run the workflow daily at 9 AM EST
    - cron: '0 14 * * *'  # This will run at 9 AM EST during standard time (UTC-5)
    - cron: '0 13 * * *'  # This will run at 9 AM EST during daylight saving time (UTC-4)
  workflow_dispatch:  # This enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access your scripts
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run your script (adjust the script path as needed)
      - name: Run the script
        run: |
          python3 test_chatops.py
