name: Run Daily Script

on:
  schedule:
    # Run the workflow daily at 9 AM EST
    - cron: '0 13 * * *'  # This will run at 9 AM EST during daylight saving time (UTC-4)
  workflow_dispatch:  # Enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access your scripts
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your required Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your script with environment variable
      - name: Run the script
        env:
          TEAMS_ACCESS_TOKEN: ${{ secrets.TEAMS_ACCESS_TOKEN }}
        run: |
          python3 chatops.py
