name: Run Chatops

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI
  schedule:
    - cron: '0 14 * * *'  # Run every day at 14:00 UTC (7:00 AM PST)

jobs:
  run-chatops:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment
        run: |
          echo "Python version: $(python3 --version)"
          echo "Python executable: $(which python3)"
          echo "Environment variables:"
          env | sort
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          LI_ACCESS_TOKEN: ${{ secrets.LI_ACCESS_TOKEN }}
          PROFILE_ID: ${{ secrets.PROFILE_ID }}

      - name: Run Chatops
        run: python3 chatops.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          LI_ACCESS_TOKEN: ${{ secrets.LI_ACCESS_TOKEN }}
          PROFILE_ID: ${{ secrets.PROFILE_ID }}
